### ISSUE TITLE
Create comp rocket sled

### ISSUE THREAD

**Issue by varun-un** [Terrapin-Rocket-Team/SRAD-Avionics#173]

**Comment by DrewBrandt** [comment]
Some refinements are needed:

- [ ] Allow Radio Teensy to be accessed by USB while mounted
- [ ] Zip Tie holes for FC battery
- [ ] Less platform area where not needed so that Sunjum can see down into the COTS section
- [ ] Slight fillet on the area where the spacers meet the platform to make that section a bit stronger
- [ ] Allow Radio antenna to be straightened while board is mounted (i.e. cut out the hole so the antenna can fold in and out of it)
- [ ] .
- [ ] Anything else?
